/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package util.zx0;

import java.io.File;
import java.io.FileInputStream;
import util.ZX0Wrapper;

/**
 *
 * @author santi
 */
public class Test {
    public static void main(String args[]) throws Exception
    {
        String testFile = "src/autogenerated/title-tiles.bin";
        String tmpFile = "tmp/tmp.zx0";

        File f = new File(testFile);
        FileInputStream fis = new FileInputStream(f);
        byte input_data[] = fis.readAllBytes();
        System.out.println("Original size: " + input_data.length);

        // try the original method:
        int size = ZX0Wrapper.main(testFile, tmpFile, true, false);
        System.out.println("C++ ZX0 compressed file: " + size);
        File f2 = new File(tmpFile);
        FileInputStream fis2 = new FileInputStream(f2);
        byte expected_data[] = fis2.readAllBytes();
        
        // try my converted Java method:
        byte compressed[] = ZX0.compress(input_data, 0, ZX0.MAX_OFFSET_ZX0);
        System.out.println("Java ZX0 compressed file: " + compressed.length);
        
        for(int i = 0;i<expected_data.length;i++) {
            if (compressed[i] != expected_data[i]) { 
                System.out.println("Difference in byte " + i + ": " + expected_data[i] + " vs " + compressed[i]);
            }
        }
    }
}
