/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package westen;

import PNGtoMSX.ConvertPatternsToAssembler;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import util.Pletter;
import util.Z80Assembler;
import util.ZX0Wrapper;

/**
 *
 * @author santi
 */
public class Inventory {
    
    static int TOLERANCE = 64;
    
    public static void main(String args[]) throws Exception
    {
        String objectsImageFileName = "data/objects.png";
        String outputFolder = "src/autogenerated";
        
        ConvertPatternsToAssembler.MSX1Palette = Walls.MSX1Palette;
        BufferedImage img = ImageIO.read(new File(objectsImageFileName));

        // First 1024 bytes:
        {
            List<Integer> data = new ArrayList<>();
//            addInventoryItem(img, 16, 13, data);  // jump
//            addInventoryItem(img, 18, 13, data);  // use

            addInventoryItem(img, 0, 0, data);  // stool
            addInventoryItem(img, 2, 3, data);  // yellow key
            addInventoryItem(img, 4, 3, data);  // gun
            addInventoryItem(img, 0, 5, data);  // white key
            addInventoryItem(img, 2, 5, data);  // 1/2 key 1
            addInventoryItem(img, 4, 5, data);  // 1/2 key 2
            addInventoryItem(img, 18, 3, data);  // 1/2 key merged
            addInventoryItem(img, 20, 3, data);  // letter1
            addInventoryItem(img, 22, 3, data);  // lamp
            addInventoryItem(img, 0, 16, data);  // oil
            addInventoryItem(img, 2, 16, data);  // heart
            addInventoryItem(img, 2, 18, data);  // book
            addInventoryItem(img, 4, 22, data);  // candle
            addInventoryItem(img, 8, 19, data);  // gun key
            addInventoryItem(img, 10, 19, data);  // green key
            addInventoryItem(img, 19, 21, data);  // diary1
            
            String outputFileName = outputFolder + "/inventory0";
            Z80Assembler.dataToBinary(data, outputFileName+".bin");
            Pletter.intMain(new String[]{outputFileName+".bin", outputFileName+".plt"});
            ZX0Wrapper.main(outputFileName+".bin", outputFileName+".zx0", true, false);
        }
        
        // Second 1024 bytes:
        {
            List<Integer> data = new ArrayList<>();

            addInventoryItem(img, 0, 30, data);  // diary2
            addInventoryItem(img, 2, 30, data);  // diary3
            addInventoryItem(img, 4, 30, data);  // backyard key
            addInventoryItem(img, 6, 30, data);  // lab notes
            addInventoryItem(img, 8, 30, data);  // hammer
            addInventoryItem(img, 10, 30, data);  // garlic
            addInventoryItem(img, 19, 30, data);  // stake
            addInventoryItem(img, 21, 30, data);  // rubbed stake
            addInventoryItem(img, 27, 28, data);  // vampire 1 note
            addInventoryItem(img, 29, 28, data);  // vampire 2 note
            
            String outputFileName = outputFolder + "/inventory1";
            Z80Assembler.dataToBinary(data, outputFileName+".bin");
            Pletter.intMain(new String[]{outputFileName+".bin", outputFileName+".plt"});
            ZX0Wrapper.main(outputFileName+".bin", outputFileName+".zx0", true, false);
        }        
    }
    
    
    public static void addInventoryItem(BufferedImage img, int x, int y, List<Integer> data) throws Exception
    {
        for(int i = 0;i<2;i++) {
            for(int j = 0;j<2;j++) {
                data.addAll(ConvertPatternsToAssembler.generateAssemblerPatternBitmap(x+j, y+i, img, TOLERANCE));
                data.addAll(ConvertPatternsToAssembler.generateAssemblerPatternAttributes(x+j, y+i, img, TOLERANCE));
            }
        }
    }    
}
