/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package westen;

import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Random;
import text.EncodeText;
import text.PAKFont;
import util.Pair;

/**
 *
 * @author santi
 */
public class Text {
    public static void main(String args[]) throws Exception
    {
        List<String> characters = new ArrayList<>();
        characters.add(" !/@'()?,-.");
        characters.add("0123456789:");
        characters.add("ABCDEFGHIJKLMNO");
        characters.add("PQRSTUVWXYZ");
        characters.add("abcdefghijklmno");
        characters.add("pqrstuvwxyzó");
        characters.add("ñ");
        PAKFont font = new PAKFont("data/font.png", characters);   
        font.generateAssemblerData("src/autogenerated/font");
        
        font.printFontInfo();
                
        // Text lines:
        List<String> lines = new ArrayList<>();
        
        HashMap<String,String> lines_with_constant = new HashMap<>();
//        lines_with_constant.put("BRAIN GAMES", "BRAIN_GAMES");
        lines_with_constant.put("Presents", "PRESENTS");

        lines_with_constant.put("London, 1898", "INTRO_MSG1");
        lines_with_constant.put("Ding Dong!", "INTRO_MSG2");
        lines_with_constant.put("Coming!", "INTRO_MSG3");
        lines_with_constant.put("A letter for you Professor", "INTRO_MSG4");
        lines_with_constant.put("Thank you Richard!", "INTRO_MSG5");
//        lines_with_constant.put("Who could it be?", "INTRO_MSG6");
        lines_with_constant.put("Let's see what does it say", "INTRO_MSG6");
        lines_with_constant.put("Terrible news!", "INTRO_MSG7");
        lines_with_constant.put("JW was a dear friend!", "INTRO_MSG8");
        lines_with_constant.put("I must go there at once!", "INTRO_MSG9");
        
        lines_with_constant.put("Dear Professor Edward Kelvin","LETTER1_LINE1");
        lines_with_constant.put("We regret to inform you of the passing of Jonathan","LETTER1_LINE2");
        lines_with_constant.put("Westen, who died on October 16th. In his will, Mr.","LETTER1_LINE3");
        lines_with_constant.put("Westen left his scientific notes to you. He also","LETTER1_LINE4");
        lines_with_constant.put("wrote a letter for you, which we encase here.","LETTER1_LINE5");
        lines_with_constant.put("We also inform you that Mrs Lucy Westen plans","LETTER1_LINE6");
        lines_with_constant.put("to take possession of the house on December 1st.","LETTER1_LINE7");

        
//        lines_with_constant.put("Dear Ed.","LETTER2_LINE1");
        lines_with_constant.put("If you are reading this, I am probably ","LETTER2_LINE2");
        lines_with_constant.put("dead. You must retrieve my scientific","LETTER2_LINE3");
        lines_with_constant.put("notes before my sister Lucy takes","LETTER2_LINE4");
        lines_with_constant.put("possession of the house. Only you will be","LETTER2_LINE5");
        lines_with_constant.put("able to understand them! Here is the key to","LETTER2_LINE6");
        lines_with_constant.put("Westen House, and part of a key that you","LETTER2_LINE7");
        lines_with_constant.put("will need to reach my laboratory. It is","LETTER2_LINE8");
        lines_with_constant.put("important to me.","LETTER2_LINE9");
//        lines_with_constant.put("JW","LETTER2_LINE10");
        
        lines_with_constant.put("Safe: 15-30-10", "LETTER3_LINE1_SECRET");
        lines_with_constant.put("Dear Ed,", "LETTER3_LINE1");
        lines_with_constant.put("I hope you find this before my family", "LETTER3_LINE2");
        lines_with_constant.put("does. It holds the secret to the second", "LETTER3_LINE3");
        lines_with_constant.put("half of the key you should already have.", "LETTER3_LINE4");
        lines_with_constant.put("I used lemon ink. You will know what to do.", "LETTER3_LINE5");
        lines_with_constant.put("You'll soon understand the secretiveness.", "LETTER3_LINE6");
        lines_with_constant.put("JW", "LETTER3_LINE7");
        
//        lines_with_constant.put("Dear Ed,", "LETTER4_LINE1");
        lines_with_constant.put("Now that you have seen the house firsthand", "LETTER4_LINE2");
        lines_with_constant.put("you might have already guessed. My family's", "LETTER4_LINE3");
        lines_with_constant.put("name is not Westen, but Westenra.", "LETTER4_LINE4");
        lines_with_constant.put("We hid our name to hide my sister's identity.", "LETTER4_LINE5");
        lines_with_constant.put("As you might recall, Lucy Westenra was", "LETTER4_LINE6");
        lines_with_constant.put("involved in an unfortunate accident two years", "LETTER4_LINE7");
        lines_with_constant.put("ago in an encounter with a creature they call", "LETTER4_LINE8");
        lines_with_constant.put("a vampire. They are all vampires now Ed!", "LETTER4_LINE9");
        lines_with_constant.put("She did not die as the news said, and she", "LETTER4_LINE10");
        lines_with_constant.put("is not alone. But I have a plan. I know how", "LETTER4_LINE11");
        lines_with_constant.put("to kill them. Seek their coffins, they sleep", "LETTER4_LINE12");
        lines_with_constant.put("there. Rub them with garlic before they", "LETTER4_LINE13");
        lines_with_constant.put("arrive, and they will perish in their sleep!", "LETTER4_LINE14");
        lines_with_constant.put("Work quickly! Prepare it before they arrive!", "LETTER4_LINE15");
        lines_with_constant.put("If you are too late, killing them will be hard!", "LETTER4_LINE16");
        lines_with_constant.put("You will need to drive a stake rubbed", "LETTER4_LINE17");
        lines_with_constant.put("in garlic into their hearts while they sleep.", "LETTER4_LINE18");
        lines_with_constant.put("I hope you do not need to resort to this!", "LETTER4_LINE19");
        lines_with_constant.put("Best of luck! JW", "LETTER4_LINE20");
        
        lines_with_constant.put("P.S.:", "LETTER5_LINE0");
        lines_with_constant.put("Vampires in my family sleep in coffins in", "LETTER5_LINE1");
        lines_with_constant.put("the basement of the house. I noticed they", "LETTER5_LINE2");
        lines_with_constant.put("locked their doors with a combination lock.", "LETTER5_LINE3");
        lines_with_constant.put("I think they used their vampire names as", "LETTER5_LINE4");
        lines_with_constant.put("the pass words. Vampires keep their names", "LETTER5_LINE5");
        lines_with_constant.put("secretively, but probably you can find them", "LETTER5_LINE6");
        lines_with_constant.put("by searching their rooms for diaries or", "LETTER5_LINE7");
        lines_with_constant.put("other notes.", "LETTER5_LINE8");

        lines_with_constant.put("John Seward's Diary.", "DIARY1_LINE1");
        lines_with_constant.put("...", "DIARY1_LINE2");
        lines_with_constant.put("July 7th, 1897", "DIARY1_LINE3");
        lines_with_constant.put("Mrs Lucy finally made me part of her inner", "DIARY1_LINE4");
        lines_with_constant.put("circle! I will now use the name of this month", "DIARY1_LINE5");
        lines_with_constant.put("as my own to remember this occasion!", "DIARY1_LINE6");

        lines_with_constant.put("Arthur Holmwood's Diary.", "DIARY2_LINE1");
//        lines_with_constant.put("...", "DIARY2_LINE2");
        lines_with_constant.put("June 26th, 1897", "DIARY2_LINE3");
        lines_with_constant.put("My beloved finally converted me. This is", "DIARY2_LINE4");
        lines_with_constant.put("exhilarating. I need to choose a name now.", "DIARY2_LINE5");
        lines_with_constant.put("I think I will pick her family name to", "DIARY2_LINE6");
        lines_with_constant.put("show my devotion.", "DIARY2_LINE7");
        
        lines_with_constant.put("Santiago Ontañón 2021", "CREDITS");
        lines_with_constant.put("Press SPACE to Start", "START");
        lines_with_constant.put("Press M for controls", "CONTROLS");
        
        lines_with_constant.put("Game Over", "GAME_OVER");
        
        lines_with_constant.put("Joystick / arrow keys to move.", "TUTORIAL1_LINE1");
        lines_with_constant.put("Button 1 / space to jump.", "TUTORIAL1_LINE2");

        lines_with_constant.put("While holding Button 2 / M:", "TUTORIAL2_LINE1");
        lines_with_constant.put("- Joystick / arrow keys to", "TUTORIAL2_LINE2");
        lines_with_constant.put("  select inventory items,", "TUTORIAL2_LINE3");
        lines_with_constant.put("- Button 1 / space to use them.", "TUTORIAL2_LINE4");
        
        lines_with_constant.put("Some objects can be pushed by", "TUTORIAL3_LINE1");
        lines_with_constant.put("walking into them.", "TUTORIAL3_LINE2");

        lines_with_constant.put("To interact with a room object: get", "TUTORIAL4_LINE1");
        lines_with_constant.put("close by with an empty inventory slot", "TUTORIAL4_LINE2");
        lines_with_constant.put("selected, and press Button 1 / space", "TUTORIAL4_LINE3");
        lines_with_constant.put("while holding Button 2 / m.", "TUTORIAL4_LINE4");
        lines_with_constant.put("To pick it up: do the same while", "TUTORIAL4_LINE5");
        lines_with_constant.put("standing on top of the object.", "TUTORIAL4_LINE6");
        
//        lines_with_constant.put("A note from JW! Let's read it!", "LETTER1");

        lines_with_constant.put("I just arrived at Westen House.", "GAME_START_MESSSAGE1");
        lines_with_constant.put("Let's find JW's laboratory.", "GAME_START_MESSSAGE2");        
        
        lines_with_constant.put("I'll leave the stools behind.", "DROP_STOOLS");
        lines_with_constant.put("A note from JW! Let's read it!", "LETTER3");

        lines_with_constant.put("Nothing here to use or pick up.", "USE_ERROR");
        lines_with_constant.put("There is no lock here to unlock.", "ITEM_KEY");
        lines_with_constant.put("Looks like the key for a chest.", "ITEM_KEY_GUN");
        lines_with_constant.put("I need to find the other half.", "ITEM_HALF_KEY");
        lines_with_constant.put("A bottle of lamp oil.", "ITEM_OIL");
        lines_with_constant.put("I'll refill the lamp with this oil.", "ITEM_OIL_USED");
        lines_with_constant.put("An oil lamp. It's out of oil.", "ITEM_LAMP");
        lines_with_constant.put("An oil lamp. The flame is on.", "ITEM_LAMP_ON");
        lines_with_constant.put("The lamp heat is developing", "USE_LAMP1");
        lines_with_constant.put("the lemon ink in the letter!", "USE_LAMP2");
        lines_with_constant.put("There is nothing behind this painting.", "USE_PAINTING");
        lines_with_constant.put("Look! A safe behind this painting!", "USE_PAINTING_SAFE");
        lines_with_constant.put("I don't know the combination.", "USE_SAFE");
        lines_with_constant.put("Aha! The letter code worked!", "USE_SAFE_OPEN1");
        lines_with_constant.put("There is nothing else inside.", "USE_SAFE_OPEN2");
        lines_with_constant.put("The two halves fit perfectly!", "MERGE_RED_KEY");
        lines_with_constant.put("There is a loose page.", "USE_BOOK");
        lines_with_constant.put("I don't want to put the candle here.", "USE_CANDLE");
        
        lines_with_constant.put("Quincey Morris, 1862 - 1897", "USE_TOMBSTONE");
        lines_with_constant.put("This door is locked.", "USE_DOOR");
        lines_with_constant.put("Lots of books about the dark arts.", "USE_BOOK_STACK");
        lines_with_constant.put("This chest is just decorative.", "USE_CHEST");
        lines_with_constant.put("I don't feel like going now.", "USE_TOILET");
        lines_with_constant.put("No time for a bath now.", "USE_BATHTUB");
        lines_with_constant.put("A very nice gramophone.", "USE_GRAMOPHONE");
        lines_with_constant.put("A violin, I can't play it.", "USE_VIOLIN");
        lines_with_constant.put("No need to wash my hands now.", "USE_SINK");
        lines_with_constant.put("This window doesn't open.", "USE_WINDOW");
        lines_with_constant.put("A very expensive-looking coffin.", "USE_COFFIN");
        lines_with_constant.put("These are human remains!", "USE_BONES");  
        lines_with_constant.put("This chest is locked.", "USE_CHEST_GUN1");
        lines_with_constant.put("Nothing else in this chest.", "USE_CHEST_GUN2");
        lines_with_constant.put("The key opened the chest.", "TAKE_GUN1");
        lines_with_constant.put("There was a revolver inside!", "TAKE_GUN2");
        
        lines_with_constant.put("An accounting book. It's strange", "USE_BOOK_WESTENRA1");
        lines_with_constant.put("though. Since instead of Westen,", "USE_BOOK_WESTENRA2");
        lines_with_constant.put("this is for the Westenra family...", "USE_BOOK_WESTENRA3");
        
        lines_with_constant.put("This is the diary of Lucy Westenra.", "USE_DIARY3_1");
        lines_with_constant.put("Most pages are torn, but I found", "USE_DIARY3_2");
        lines_with_constant.put("a key inside.", "USE_DIARY3_3");

        lines_with_constant.put("So, Lucy Westen is Lucy Westenra!", "USE_LAB_NOTES_1");
        lines_with_constant.put("This is worse than I thought!", "USE_LAB_NOTES_2");
        lines_with_constant.put("I need to hurry and find garlic!", "USE_LAB_NOTES_3");

        lines_with_constant.put("This crate looks fairly weak...", "USE_BREAKABLE_CRATE");
        lines_with_constant.put("Nothing I can break nearby.", "USE_HAMMER1");
        lines_with_constant.put("I smashed it with the hammer!", "USE_HAMMER2");

        lines_with_constant.put("A clove of garlic.", "USE_GARLIC1");
        lines_with_constant.put("I rubbed the stake with the garlic.", "USE_GARLIC2");
        lines_with_constant.put("A wooden stake.", "USE_STAKE");
        lines_with_constant.put("A wooden stake rubbed in garlic.", "USE_RUBBED_STAKE");
        lines_with_constant.put("Not now! The vampire is awake!", "USE_RUBBED_STAKE_AWAKE");
        lines_with_constant.put("I need to get closer!", "USE_RUBBED_STAKE_TOO_FAR");
        lines_with_constant.put("It worked! I killed it!", "USE_RUBBED_STAKE_KILL");

        lines_with_constant.put("The door has a combination lock.", "USE_VAMPIRE_DOOR");
        
        lines_with_constant.put("How strange, this part of the", "MSG_ABANDONED1");
        lines_with_constant.put("house looks abandoned...", "MSG_ABANDONED2");

        lines_with_constant.put("This room is full of books about", "MSG_BOOKS1");
        lines_with_constant.put("the dark arts!", "MSG_BOOKS2");
        lines_with_constant.put("Why would JW have these!", "MSG_BOOKS3");

        lines_with_constant.put("What is this?! Was JW conducting", "MSG_PENTAGRAM1");
        lines_with_constant.put("unholy rituals?!", "MSG_PENTAGRAM2");

        lines_with_constant.put("The door opened! I thought I was", "MSG_PENTAGRAM_SOLVED1");
        lines_with_constant.put("just looking for JW's lab, but this", "MSG_PENTAGRAM_SOLVED2");
        lines_with_constant.put("house is stranger than I thought!", "MSG_PENTAGRAM_SOLVED3");
        
        lines_with_constant.put("Human remains!", "MSG_FEEDING1");
        lines_with_constant.put("Ok, it is now clear that something", "MSG_FEEDING2");
        lines_with_constant.put("macabre was going on in this house!", "MSG_FEEDING3");

        lines_with_constant.put("At last! JW's laboratory!", "MSG_LAB");

        lines_with_constant.put("Wait, I hear noises downstairs!", "MSG_FAMILY_CUTSCENE1");
        lines_with_constant.put("Arthur: At last! That brother of yours is dead!", "MSG_FAMILY_CUTSCENE2");
        lines_with_constant.put("Lucy: Indeed! The house is now mine!", "MSG_FAMILY_CUTSCENE3");
        lines_with_constant.put("Lucy: I longed for entering my basement in peace!", "MSG_FAMILY_CUTSCENE4");
        lines_with_constant.put("Lucy: From this house we will build our family!!", "MSG_FAMILY_CUTSCENE5");
        lines_with_constant.put("Lucy: Today it's only us, but tomorrow we will grow!!", "MSG_FAMILY_CUTSCENE6");
        lines_with_constant.put("Lucy: Hahaha", "MSG_FAMILY_CUTSCENE7A");
        lines_with_constant.put("John: Hahaha", "MSG_FAMILY_CUTSCENE7B");
        lines_with_constant.put("Arthur: Hahaha", "MSG_FAMILY_CUTSCENE7C");
        lines_with_constant.put("Lucy: But today we rest! Let's go!", "MSG_FAMILY_CUTSCENE8");

        lines_with_constant.put("I cannot believe my eyes!", "MSG_FAMILY_CUTSCENE9");
        lines_with_constant.put("They are here! I was too slow!", "MSG_FAMILY_CUTSCENE10");
        lines_with_constant.put("I will need to use the stakes...", "MSG_FAMILY_CUTSCENE11");
        
        lines_with_constant.put("It opened!", "OPEN_VAMPIRE1_DOOR");
        lines_with_constant.put("I don't need this diary anymore...", "OPEN_VAMPIRE1_DOOR2");
        lines_with_constant.put("A vampire!", "ENTER_VAMPIRE_ROOM1");
        lines_with_constant.put("I'll approach while it sleeps...", "ENTER_VAMPIRE_ROOM2");

        lines_with_constant.put("This must be Lucy!", "ENTER_VAMPIRE3_ROOM1");
        lines_with_constant.put("I did it! Lucy is dead!", "ENTER_VAMPIRE3_ROOM2");
        
        lines_with_constant.put("I found a note in the corpse.", "FIND_VAMPIRE_NOTE");
        
        lines_with_constant.put("John Seward's to do:", "VAMPIRE1_NOTE1");
        lines_with_constant.put("- Kill JW (done)", "VAMPIRE1_NOTE2");
        lines_with_constant.put("- Find my diary", "VAMPIRE1_NOTE3");
        lines_with_constant.put("- Thank Lucy for using our initials to", "VAMPIRE1_NOTE4");
        lines_with_constant.put("  form her vampire name. Such an honor", "VAMPIRE1_NOTE5");
        lines_with_constant.put("  for all three of us!", "VAMPIRE1_NOTE6");

        lines_with_constant.put("Lucy, why did you need to use also the", "VAMPIRE2_NOTE1");
        lines_with_constant.put("initials from those two? I am your", "VAMPIRE2_NOTE2");
        lines_with_constant.put("husband! At least you put mine first...", "VAMPIRE2_NOTE3");
        lines_with_constant.put("Arthur Holmwood", "VAMPIRE2_NOTE4");
                
        
        lines_with_constant.put("December 2nd, 1898", "ENDING_LINE1");
        
        lines_with_constant.put("I still don't know how to feel", "ENDING_LINE2");
        lines_with_constant.put("about the events that took", "ENDING_LINE3");
        lines_with_constant.put("place in Westen... I mean", "ENDING_LINE4");
        lines_with_constant.put("Westenra house...", "ENDING_LINE5");

        lines_with_constant.put("Although I am relieved to have", "ENDING_LINE6");
        lines_with_constant.put("rid the world of those beasts", "ENDING_LINE7");
        lines_with_constant.put("and have come out alive, I am", "ENDING_LINE8");
        lines_with_constant.put("saddened to learn that the life", "ENDING_LINE9");
        lines_with_constant.put("of my good friend came to an", "ENDING_LINE10");
        lines_with_constant.put("end because of such creatures...", "ENDING_LINE11");

        lines_with_constant.put("I really hope I do not need to", "ENDING_LINE12");
        lines_with_constant.put("ever return to this house...", "ENDING_LINE13");

        lines_with_constant.put("Professor Edward Kelvin", "ENDING_LINE14");

        lines_with_constant.put("Thank you for playing", "ENDING2_LINE1");
        lines_with_constant.put("Westen House", "ENDING2_LINE2");
        lines_with_constant.put("Santiago Ontañón, 2021", "ENDING2_LINE3");
        lines_with_constant.put("santi.ontanon@gmail.com", "ENDING2_LINE4");
        lines_with_constant.put("Beta testing: Jordi Sureda", "ENDING2_LINE5");
        
        
        List<Integer> capitals = font.convertStringToAssembler("ABCDEFGHIJKLMNOPQRSTUVWXYZ ");
        System.out.println("Capitals: " + capitals);
        
        
        for(String s:lines_with_constant.keySet()) {
            if (!lines.contains(s)) lines.add(s);
        }


        // List<String> newlines = lines;
        List<String> newlines = optimizeGrouppings(lines, font, 512);
        // List<String> newlines = optimizeGrouppings(lines, font, 600);
        // List<String> newlines = optimizeGrouppings(lines, font, 640);
        // List<String> newlines = optimizeGrouppings(lines, font, 700);
//         List<String> newlines = optimizeGrouppings(lines, font, 4096);
        
        HashMap<String, Pair<Integer, Integer>> ids = new HashMap<>();
        Pair<List<Integer>,List<Integer>> sizes = EncodeText.encodeTextInBanks(newlines, font, 512, "src/autogenerated", ids, "zx0");
        int size_before = 0;
        int size_after = 0;
        for(Integer size:sizes.m_a) size_before += size;
        for(Integer size:sizes.m_b) size_after += size;
        System.out.println("Total size before: " + size_before);
        System.out.println("Total size after: " + size_after);
        // String constants:
        {
            FileWriter fw = new FileWriter(new File("src/autogenerated/text-constants.asm"));
            for(String s:lines_with_constant.keySet()) {
                fw.write("TEXT_"+lines_with_constant.get(s)+"_BANK:   equ " + ids.get(s).m_a + "\n");
                fw.write("TEXT_"+lines_with_constant.get(s)+"_IDX:   equ " + ids.get(s).m_b + "\n");            
            }
            fw.flush();
            fw.close();
        }
    }
    
    
    public static List<String>  optimizeGrouppings(List<String> input_lines, PAKFont font, int group_size) throws Exception
    {
        List<String> bestLines = null;
//        EncodeText.compressor = "zx0";
        int best_size = 0;
        int best_seed = 0;      // seed 234: 1899 (for group_size 512, with 0.5 lateral moves)
                                // seed 0: 1903 (for group size 600)
                                // seed 3: 1874 (for group size 640)
                                // seed 6: 1850 (for group size 700)
        for(int seed = 0;seed<0+1;seed++) {
//        for(int seed = 0;seed<1000;seed++) {
//        for(int seed = 234;seed<234+1;seed++) {

            Pair<List<String>,Integer> tmp = optimizeGrouppingsInternal(input_lines, font, group_size, seed);
            if (bestLines == null || tmp.m_b < best_size) {
                bestLines = tmp.m_a;
                best_size = tmp.m_b;
                best_seed = seed;
                System.out.println("new best_size: " + best_size + " (best_seed: " + best_seed + ")");
            }
        }
        
        System.out.println("final best_size: " + best_size + " (best_seed: " + best_seed + ")");
        return bestLines;
    }
    
    
    public static Pair<List<String>,Integer>  optimizeGrouppingsInternal(List<String> input_lines, PAKFont font, int group_size, int seed) throws Exception  
    {
        String compressorDuringOptimization = "pletter";
        String targetCompressor = "zx0";
        Random r = new Random();
        r.setSeed(seed);

        List<String> lines = new ArrayList<>();
        lines.addAll(input_lines);
        Collections.shuffle(lines, r);
        int initial_size = EncodeText.estimateSizeOfAllTextBanks(lines, font, group_size, compressorDuringOptimization);
        int best = initial_size;
        System.out.println("Original order size: " + initial_size + " (with target compressor: " + 
                EncodeText.estimateSizeOfAllTextBanks(lines, font, group_size, targetCompressor) + ")");
        System.out.println("Initial size (seed " + seed + "):" + initial_size);

        double threshold = 1.0; // 1.0 means doing it sistematically, lower values run faster, but might not result in the best results
        double temperature = 0.0;
        double temperature_decay = 0.8;
        boolean repeat = true;
        // boolean repeat = false;
        while(repeat){
            repeat = false;
            System.out.println("temperature: " + temperature);
            for(int idx1 = 0;idx1<lines.size();idx1++) {
                // System.out.println(idx1 + "");
                for(int idx2 =idx1+1;idx2<lines.size();idx2++) {
                    if (r.nextDouble() > threshold) continue;
                    String tmp1 = lines.get(idx1);
                    String tmp2 = lines.get(idx2);
                    lines.set(idx1, tmp2);
                    lines.set(idx2, tmp1);

                    int size = EncodeText.estimateSizeOfAllTextBanks(lines, font, group_size, compressorDuringOptimization);
                    if (size < best) {
                        System.out.print(size + " ");
                        best = size;
                        repeat = true;
                    } else if (size == best && r.nextDouble() > 0.5) {
                        System.out.print(size + "* ");
                        best = size;
                        // repeat = true;
                    } else {
                        if (r.nextDouble() > temperature) {
                            // undo the swap:
                            lines.set(idx1, tmp1);
                            lines.set(idx2, tmp2);
                        } else {
                            System.out.println("- temperature ("+temperature+") induced random swap: " + size);
                            best = size;
                            repeat = true;                            
                        }
                    }
                }
            }
            System.out.println("");
            temperature *= temperature_decay;
            /*
            if (!repeat && !compressorDuringOptimization.equals(targetCompressor)) {
                // At the end do one round with the target compressor:
                compressorDuringOptimization = targetCompressor;
                best = EncodeText.estimateSizeOfAllTextBanks(lines, font, group_size, targetCompressor);
                repeat = true;
            }*/
            // repeat = false;
        }
        
        // System.out.println(lines);
        System.out.println("After optimization: " + EncodeText.estimateSizeOfAllTextBanks(lines, font, group_size, targetCompressor));
        
        return new Pair<>(lines, best);
    }
}
