/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package westen;

import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Random;
import text.EncodeText;
import text.PAKFont;
import util.Pair;

/**
 *
 * @author santi
 */
public class TextES {
    public static PAKFont font = null;
    
    public static void main(String args[]) throws Exception
    {
        List<String> characters = new ArrayList<>();
        characters.add(" !/@'()?,-.");
        characters.add("0123456789:");
        characters.add("ABCDEFGHIJKLMNO");
        characters.add("PQRSTUVWXYZ");
        characters.add("abcdefghijklmno");
        characters.add("pqrstuvwxyzáéíóú");
        characters.add("ñ");
        font = new PAKFont("data/font-es.png", characters);   
        font.generateAssemblerData("src/autogenerated/font-es");
        
        font.printFontInfo();
                
        // Text lines:
        List<String> lines = new ArrayList<>();
        
        HashMap<String,String> lines_with_constant = new HashMap<>();
//        addLineSafe(lines_with_constant, "BRAIN GAMES", "BRAIN_GAMES");
        addLineSafe(lines_with_constant, "Presenta", "PRESENTS", 8);

        addLineSafe(lines_with_constant, "Londres, 1898", "INTRO_MSG1", 8);
        addLineSafe(lines_with_constant, "Ding Dong!", "INTRO_MSG2", 8);
        addLineSafe(lines_with_constant, "Ya voy!", "INTRO_MSG3", 8);
        addLineSafe(lines_with_constant, "Carta para usted, profesor", "INTRO_MSG4", 16);
        addLineSafe(lines_with_constant, "Gracias Richard!", "INTRO_MSG5", 12);
        addLineSafe(lines_with_constant, "A ver que dice!", "INTRO_MSG6", 16);
        addLineSafe(lines_with_constant, "Malísias notícias!", "INTRO_MSG7", 12);
        addLineSafe(lines_with_constant, "JW era un gran amigo!", "INTRO_MSG8", 12);
        addLineSafe(lines_with_constant, "Debo ir de inmediato!", "INTRO_MSG9", 14);
        
        addLineSafe(lines_with_constant, "Querido Profesor Edward Kelvin","LETTER1_LINE1", 28);
        addLineSafe(lines_with_constant, "Nos apena informarle de la muerte de Jonathan","LETTER1_LINE2", 28);
        addLineSafe(lines_with_constant, "Westen, fallecido el 16 de octubre. En su voluntad,","LETTER1_LINE3", 28);
        addLineSafe(lines_with_constant, "El Sr. Westen le dejó su cuaderno científico. Y","LETTER1_LINE4", 28);
        addLineSafe(lines_with_constant, "también una carta, que le adjuntamos aquí.","LETTER1_LINE5", 28);
        addLineSafe(lines_with_constant, "Le informamos también que la Señora Lucy Westen","LETTER1_LINE6", 28);
        addLineSafe(lines_with_constant, "tomará posesión de la casa el 1 de diciembre.","LETTER1_LINE7", 28);
        
//        addLineSafe(lines_with_constant, "Dear Ed.","LETTER2_LINE1");
        addLineSafe(lines_with_constant, "Si está leyendo ésto, probablemente estoy","LETTER2_LINE2", 24);
        addLineSafe(lines_with_constant, "muerto. Debe encontrar mi cuaderno antes","LETTER2_LINE3", 24);
        addLineSafe(lines_with_constant, "de que mi hermana Lucy tome posesión de la","LETTER2_LINE4", 24);
        addLineSafe(lines_with_constant, "casa. Solo usted es capaz de comprenderlo!","LETTER2_LINE5", 24);
        addLineSafe(lines_with_constant, "Le adjunto la llave de la mansión Westen, ","LETTER2_LINE6", 24);
        addLineSafe(lines_with_constant, "y parte de una llave que le será necesaria","LETTER2_LINE7", 24);
        addLineSafe(lines_with_constant, "para llegar a mi laboratorio. Por favor, es","LETTER2_LINE8", 24);
        addLineSafe(lines_with_constant, "importante para mi.","LETTER2_LINE9", 24);
//        addLineSafe(lines_with_constant, "JW","LETTER2_LINE10");
        
        addLineSafe(lines_with_constant, "Combinación: 15-30-10", "LETTER3_LINE1_SECRET", 12);
        addLineSafe(lines_with_constant, "Querido Ed,", "LETTER3_LINE1", 22);
        addLineSafe(lines_with_constant, "Espero que encuentre esto ántes que mi", "LETTER3_LINE2", 22);
        addLineSafe(lines_with_constant, "familia. Contiene la clave que le llevará", "LETTER3_LINE3", 22);
        addLineSafe(lines_with_constant, "a la segunda parte de la llave que tiene.", "LETTER3_LINE4", 22);
        addLineSafe(lines_with_constant, "Usé tinta de limón. Usted sabrá qué", "LETTER3_LINE5", 22);
        addLineSafe(lines_with_constant, "hacer. Pronto entenderá la prudéncia.", "LETTER3_LINE6", 22);
        addLineSafe(lines_with_constant, "JW", "LETTER3_LINE7", 22);
        
//        addLineSafe(lines_with_constant, "Querido Ed,", "LETTER4_LINE1");
        addLineSafe(lines_with_constant, "Ahora que ha visto la casa con sus propios", "LETTER4_LINE2", 24);
        addLineSafe(lines_with_constant, "ojos, quizás ya se haya dado cuenta. Mi", "LETTER4_LINE3", 24);
        addLineSafe(lines_with_constant, "apellido no es Westen, es Westenra.", "LETTER4_LINE4", 24);
        addLineSafe(lines_with_constant, "Ocultamos nuestro nombre para proteger a", "LETTER4_LINE5", 24);
        addLineSafe(lines_with_constant, "mi hermana. Como recordará, Lucy Westenra", "LETTER4_LINE6", 24);
        addLineSafe(lines_with_constant, "sufrió un horrible accidente dos años atrás", "LETTER4_LINE7", 24);
        addLineSafe(lines_with_constant, "en un encuentro con una criatura a la que", "LETTER4_LINE8", 24);
        addLineSafe(lines_with_constant, "llaman un vampiro. Ed, son todos vampiros!", "LETTER4_LINE9", 24);
        addLineSafe(lines_with_constant, "No murió tal como se reportó... y no está", "LETTER4_LINE10", 24);
        addLineSafe(lines_with_constant, "sola. Pero tengo un plan! Sé como matarlos!", "LETTER4_LINE11", 24);
        addLineSafe(lines_with_constant, "Busque sus ataudes, allí es donde duermen.", "LETTER4_LINE12", 24);
        addLineSafe(lines_with_constant, "Frótelos con ajo antes de que lleguen", "LETTER4_LINE13", 24);
        addLineSafe(lines_with_constant, "y así moriran mientras duermen! Pero", "LETTER4_LINE14", 24);
        addLineSafe(lines_with_constant, "apresurese! Preparelo ántes de que lleguen!", "LETTER4_LINE15", 24);
        addLineSafe(lines_with_constant, "Si se demora, matarlos será más difícil!", "LETTER4_LINE16", 24);
        addLineSafe(lines_with_constant, "Deberá clavar una estaca frotada con ajo", "LETTER4_LINE17", 24);
        addLineSafe(lines_with_constant, "en su corazón, mienstras duermen!", "LETTER4_LINE18", 24);
        addLineSafe(lines_with_constant, "Espero que no deba recurrir a ese método...", "LETTER4_LINE19", 24);
        addLineSafe(lines_with_constant, "Le deseo suerte! JW", "LETTER4_LINE20", 24);

        addLineSafe(lines_with_constant, "P.S.:", "LETTER5_LINE0", 24);
        addLineSafe(lines_with_constant, "Los vampiros de mi familia duermen en", "LETTER5_LINE1", 24);
        addLineSafe(lines_with_constant, "ataudes en el sótano. Ví que usan", "LETTER5_LINE2", 24);
        addLineSafe(lines_with_constant, "cerraduras de combinación en las puertas.", "LETTER5_LINE3", 24);
        addLineSafe(lines_with_constant, "Creo que usaron sus nombres vampíricos", "LETTER5_LINE4", 24);
        addLineSafe(lines_with_constant, "como claves. Mantienen sus nombres", "LETTER5_LINE5", 24);
        addLineSafe(lines_with_constant, "en secreto, pero quizás haya pistas", "LETTER5_LINE6", 24);
        addLineSafe(lines_with_constant, "en sus diarios y otros escritos que", "LETTER5_LINE7", 24);
        addLineSafe(lines_with_constant, "pueda encontrar en la casa.", "LETTER5_LINE8", 24);

        addLineSafe(lines_with_constant, "Diario de John Seward.", "DIARY1_LINE1", 24);
        addLineSafe(lines_with_constant, "...", "DIARY1_LINE2", 24);
        addLineSafe(lines_with_constant, "7 de julio, 1897", "DIARY1_LINE3", 24);
        addLineSafe(lines_with_constant, "Lucy al fin me hizo parte de su círculo!", "DIARY1_LINE4", 24);
        addLineSafe(lines_with_constant, "Para recordar esta ocasión usaré el", "DIARY1_LINE5", 24);
        addLineSafe(lines_with_constant, "nombre de este mes como el mío propio!", "DIARY1_LINE6", 24);

        addLineSafe(lines_with_constant, "Diario de Arthur Holmwood.", "DIARY2_LINE1", 24);
//        addLineSafe(lines_with_constant, "...", "DIARY2_LINE2", 24);
        addLineSafe(lines_with_constant, "26 de junio, 1897", "DIARY2_LINE3", 24);
        addLineSafe(lines_with_constant, "My amada por fin me ha convertido. Estoy", "DIARY2_LINE4", 24);
        addLineSafe(lines_with_constant, "en éxtasis. Ahora necesito escoger nombre.", "DIARY2_LINE5", 24);
        addLineSafe(lines_with_constant, "Usaré su apellido para demostrarle mi", "DIARY2_LINE6", 24);
        addLineSafe(lines_with_constant, "devoción.", "DIARY2_LINE7", 24);

        addLineSafe(lines_with_constant, "Santiago Ontañón 2021", "CREDITS", 16);
        addLineSafe(lines_with_constant, "ESPACIO para empezar", "START", 16);
        addLineSafe(lines_with_constant, "M para instrucciones", "CONTROLS", 16);

        addLineSafe(lines_with_constant, "Game Over", "GAME_OVER", 8);

        addLineSafe(lines_with_constant, "Joystick / cursores: caminar.", "TUTORIAL1_LINE1", 17);
        addLineSafe(lines_with_constant, "Botón 1 / espacio: saltar.", "TUTORIAL1_LINE2", 17);
        addLineSafe(lines_with_constant, "Q cambia mapeo de direcciones.", "TUTORIAL1_LINE3", 17);

        addLineSafe(lines_with_constant, "Mientras pulsas el botón 2 / M:", "TUTORIAL2_LINE1", 18);
        addLineSafe(lines_with_constant, "- Joystick / cursores para", "TUTORIAL2_LINE2", 18);
        addLineSafe(lines_with_constant, "  moverte por el inventario,", "TUTORIAL2_LINE3", 18);
        addLineSafe(lines_with_constant, "- Botón 1 / espacio para usar.", "TUTORIAL2_LINE4", 18);

        addLineSafe(lines_with_constant, "Empuja objetos caminando", "TUTORIAL3_LINE1", 17);
        addLineSafe(lines_with_constant, "contra ellos.", "TUTORIAL3_LINE2", 17);

        addLineSafe(lines_with_constant, "Para interactuar con objetos: con", "TUTORIAL4_LINE1", 20);
        addLineSafe(lines_with_constant, "un hueco vacío en el inventario", "TUTORIAL4_LINE2", 20);
        addLineSafe(lines_with_constant, "seleccionado, pulsa Botón 1 / espacio", "TUTORIAL4_LINE3", 20);
        addLineSafe(lines_with_constant, "mientras presionas el botón 2 / M.", "TUTORIAL4_LINE4", 20);
        addLineSafe(lines_with_constant, "Para cogerlos: haz lo mismo mientras", "TUTORIAL4_LINE5", 20);
        addLineSafe(lines_with_constant, "estás encima del objeto.", "TUTORIAL4_LINE6", 20);

        addLineSafe(lines_with_constant, "Acabo de llegar a la mansión Westen.", "GAME_START_MESSSAGE1", 19);
        addLineSafe(lines_with_constant, "Ahora a buscar las notas de JW!", "GAME_START_MESSSAGE2", 19);        
        addLineSafe(lines_with_constant, "Dejaré los taburetes.", "DROP_STOOLS", 19);
        addLineSafe(lines_with_constant, "Una nota de JW! Vamos a leerla!", "LETTER3", 19);

        addLineSafe(lines_with_constant, "Nada que usar por aquí.", "USE_ERROR", 19);
        addLineSafe(lines_with_constant, "No veo la cerradura adecuada.", "ITEM_KEY", 19);
        addLineSafe(lines_with_constant, "Parece la llave de un baúl.", "ITEM_KEY_GUN", 19);
        addLineSafe(lines_with_constant, "Debo encontar la otra mitad.", "ITEM_HALF_KEY", 19);
        addLineSafe(lines_with_constant, "Una botella de aceite de lámparas", "ITEM_OIL", 19);
        addLineSafe(lines_with_constant, "Rellenaré la lámpara con el aceite.", "ITEM_OIL_USED", 19);
        addLineSafe(lines_with_constant, "Una lámpara de aceite. Está vacía.", "ITEM_LAMP", 19);
        addLineSafe(lines_with_constant, "Una lámpara de aceite encendida.", "ITEM_LAMP_ON", 19);
        addLineSafe(lines_with_constant, "El calor de la lámpara ha revelado", "USE_LAMP1", 19);
        addLineSafe(lines_with_constant, "la tinta de limón en la carta!", "USE_LAMP2", 19);
        addLineSafe(lines_with_constant, "No hay nada tras este cuadro.", "USE_PAINTING", 19);
        addLineSafe(lines_with_constant, "Una caja fuerte tras el cuadro!", "USE_PAINTING_SAFE", 19);
        addLineSafe(lines_with_constant, "No sé la combinación.", "USE_SAFE", 19);
        addLineSafe(lines_with_constant, "La clave de la carta ha funcionado!", "USE_SAFE_OPEN1", 19);
        addLineSafe(lines_with_constant, "No hay nada más dentro.", "USE_SAFE_OPEN2", 19);
        addLineSafe(lines_with_constant, "Las dos mitades encajan!", "MERGE_RED_KEY", 19);
        addLineSafe(lines_with_constant, "Hay una página suelta.", "USE_BOOK", 19);
        addLineSafe(lines_with_constant, "No quiero dejar la vela aquí.", "USE_CANDLE", 19);
        addLineSafe(lines_with_constant, "Quincey Morris, 1862 - 1897", "USE_TOMBSTONE", 19);
        addLineSafe(lines_with_constant, "Está cerrada con llave.", "USE_DOOR", 19);
        addLineSafe(lines_with_constant, "Muchos libros de ocultismo.", "USE_BOOK_STACK", 19);
        addLineSafe(lines_with_constant, "Este baúl parece decorativo.", "USE_CHEST", 19);
        addLineSafe(lines_with_constant, "No necesito ir ahora mismo.", "USE_TOILET", 19);
        addLineSafe(lines_with_constant, "No tengo tiempo para baños!", "USE_BATHTUB", 19);
        addLineSafe(lines_with_constant, "Un gramophono precioso.", "USE_GRAMOPHONE", 19);
        addLineSafe(lines_with_constant, "Un violín. No sé tocarlo.", "USE_VIOLIN", 19);
        addLineSafe(lines_with_constant, "No necesito lavarme las manos.", "USE_SINK", 19);
        addLineSafe(lines_with_constant, "Esta ventana no se abre.", "USE_WINDOW", 19);
        addLineSafe(lines_with_constant, "Un ataud impresionante.", "USE_COFFIN", 19);
        addLineSafe(lines_with_constant, "Esto son restos humanos!", "USE_BONES", 19);  
        addLineSafe(lines_with_constant, "Este baúl está cerrado.", "USE_CHEST_GUN1", 19);
        addLineSafe(lines_with_constant, "No hay nada más en el baúl.", "USE_CHEST_GUN2", 19);
        addLineSafe(lines_with_constant, "La llave ha abierto el baúl.", "TAKE_GUN1", 19);
        addLineSafe(lines_with_constant, "Había un revolver dentro!", "TAKE_GUN2", 19);

        addLineSafe(lines_with_constant, "Un libro de finanzas. Pero que raro,", "USE_BOOK_WESTENRA1", 19);
        addLineSafe(lines_with_constant, "ten lugar de Westen, estas son las,", "USE_BOOK_WESTENRA2", 19);
        addLineSafe(lines_with_constant, "finanzas de la familia Westenra...", "USE_BOOK_WESTENRA3", 19);

        addLineSafe(lines_with_constant, "El diario de Lucy Westenra. La ma-", "USE_DIARY3_1", 19);
        addLineSafe(lines_with_constant, "yoría de páginas están arrancadas,", "USE_DIARY3_2", 19);
        addLineSafe(lines_with_constant, "pero había una llave dentro.", "USE_DIARY3_3", 19);
        
        addLineSafe(lines_with_constant, "Lucy Westen es Lucy Westenra!", "USE_LAB_NOTES_1", 19);
        addLineSafe(lines_with_constant, "Esto es peor de lo que imaginaba!!", "USE_LAB_NOTES_2", 19);
        addLineSafe(lines_with_constant, "Debo apresurarme y encontrar ajo!", "USE_LAB_NOTES_3", 19);

        addLineSafe(lines_with_constant, "Esta caja parece bastante floja...", "USE_BREAKABLE_CRATE", 19);
        addLineSafe(lines_with_constant, "Nada que pueda romper cerca.", "USE_HAMMER1", 19);
        addLineSafe(lines_with_constant, "He roto la caja con el martillo!", "USE_HAMMER2", 19);
        addLineSafe(lines_with_constant, "Una cabeza de ajo.", "USE_GARLIC1", 19);
        addLineSafe(lines_with_constant, "He frotado el ajo en la estaca.", "USE_GARLIC2", 19);
        addLineSafe(lines_with_constant, "Una estaca de madera.", "USE_STAKE", 19);
        addLineSafe(lines_with_constant, "Una estaca de madera con ajo.", "USE_RUBBED_STAKE", 19);
        addLineSafe(lines_with_constant, "Ahora no! El vampiro está alerta!", "USE_RUBBED_STAKE_AWAKE", 19);
        addLineSafe(lines_with_constant, "Debo acercarme más!", "USE_RUBBED_STAKE_TOO_FAR", 19);
        addLineSafe(lines_with_constant, "Ha funcionado! Lo he matado", "USE_RUBBED_STAKE_KILL", 19);
        addLineSafe(lines_with_constant, "Hay una cerradura de combinación.", "USE_VAMPIRE_DOOR", 19);
        addLineSafe(lines_with_constant, "Qué raro! Esta parte de la casa", "MSG_ABANDONED1", 19);
        addLineSafe(lines_with_constant, "parece abandonada...", "MSG_ABANDONED2", 19);

        addLineSafe(lines_with_constant, "Esta habitación está llena de", "MSG_BOOKS1", 19);
        addLineSafe(lines_with_constant, "libros de las artes oscuras!", "MSG_BOOKS2", 19);
        addLineSafe(lines_with_constant, "Por qué los tendría JW?!", "MSG_BOOKS3", 19);
        addLineSafe(lines_with_constant, "Qué es esto?! Estaba JW relizando", "MSG_PENTAGRAM1", 19);
        addLineSafe(lines_with_constant, "rituales demónicos?!", "MSG_PENTAGRAM2", 19);

        addLineSafe(lines_with_constant, "La puerta se ha abierto! Creía que", "MSG_PENTAGRAM_SOLVED1", 19);
        addLineSafe(lines_with_constant, "solo buscaba las notas de JW, pero", "MSG_PENTAGRAM_SOLVED2", 19);
        addLineSafe(lines_with_constant, "aquí hay más de lo que parece!", "MSG_PENTAGRAM_SOLVED3", 19);
        addLineSafe(lines_with_constant, "Restos humanos!", "MSG_FEEDING1", 19);
        addLineSafe(lines_with_constant, "Vale, ahora sí que está claro que", "MSG_FEEDING2", 19);
        addLineSafe(lines_with_constant, "algo macabro ocurre en esta casa!", "MSG_FEEDING3", 19);
        addLineSafe(lines_with_constant, "Por fin! El laboratorio de JW!", "MSG_LAB", 19);

        addLineSafe(lines_with_constant, "Oigo ruidos en la entrada!", "MSG_FAMILY_CUTSCENE1", 19);
        addLineSafe(lines_with_constant, "Arthur: Por fin! Ese hermano tuyo está muerto!", "MSG_FAMILY_CUTSCENE2", 31);
        addLineSafe(lines_with_constant, "Lucy: Si! La casa es ahora mía!", "MSG_FAMILY_CUTSCENE3", 31);
        addLineSafe(lines_with_constant, "Lucy: Ansiaba ya entrar en mi sótano en paz!", "MSG_FAMILY_CUTSCENE4", 31);
        addLineSafe(lines_with_constant, "Lucy: En esta casa construiremos nuestra familia!!", "MSG_FAMILY_CUTSCENE5", 31);
        addLineSafe(lines_with_constant, "Lucy: Hoy somos solo nosotros pero mañana seremos más!", "MSG_FAMILY_CUTSCENE6", 31);
        addLineSafe(lines_with_constant, "Lucy: Jajaja", "MSG_FAMILY_CUTSCENE7A", 31);
        addLineSafe(lines_with_constant, "John: Jajaja", "MSG_FAMILY_CUTSCENE7B", 31);
        addLineSafe(lines_with_constant, "Arthur: Jajaja", "MSG_FAMILY_CUTSCENE7C", 31);
        addLineSafe(lines_with_constant, "Lucy: Pero hoy descansaremos! Vamos!", "MSG_FAMILY_CUTSCENE8", 31);

        addLineSafe(lines_with_constant, "No creo lo que veo!", "MSG_FAMILY_CUTSCENE9", 19);
        addLineSafe(lines_with_constant, "Ya están aquí! He sido muy lento", "MSG_FAMILY_CUTSCENE10", 19);
        addLineSafe(lines_with_constant, "Tendré que usar las estacas...", "MSG_FAMILY_CUTSCENE11", 19);

        addLineSafe(lines_with_constant, "Se ha abierto!", "OPEN_VAMPIRE1_DOOR", 19);
        addLineSafe(lines_with_constant, "Ya no necesito este diario...", "OPEN_VAMPIRE1_DOOR2", 19);
        addLineSafe(lines_with_constant, "Un vampiro!", "ENTER_VAMPIRE_ROOM1", 19);
        addLineSafe(lines_with_constant, "Me acercaré mienstras duerme...", "ENTER_VAMPIRE_ROOM2", 19);

        addLineSafe(lines_with_constant, "Esta debe ser Lucy!", "ENTER_VAMPIRE3_ROOM1", 19);
        addLineSafe(lines_with_constant, "Lo conseguí! Lucy está muerta!", "ENTER_VAMPIRE3_ROOM2", 19);        
        addLineSafe(lines_with_constant, "Había una nota en el cadaver.", "FIND_VAMPIRE_NOTE", 19);
        
        
        addLineSafe(lines_with_constant, "Tareas de John Seward:", "VAMPIRE1_NOTE1", 24);
        addLineSafe(lines_with_constant, "- Matar a JW (hecho)", "VAMPIRE1_NOTE2", 24);
        addLineSafe(lines_with_constant, "- Encontrr mi diario", "VAMPIRE1_NOTE3", 24);
        addLineSafe(lines_with_constant, "- Agradecer a Lucy por usar nuestras ini-", "VAMPIRE1_NOTE4", 24);
        addLineSafe(lines_with_constant, "  ciales para formar su nombre vampírico.", "VAMPIRE1_NOTE5", 24);
        addLineSafe(lines_with_constant, "  Qué honor para nosotros tres!", "VAMPIRE1_NOTE6", 24);

        addLineSafe(lines_with_constant, "Lucy, por qué tuviste que usar las ini-", "VAMPIRE2_NOTE1", 22);
        addLineSafe(lines_with_constant, "ciales de esos dos? YO soy tu marido!", "VAMPIRE2_NOTE2", 22);        
        addLineSafe(lines_with_constant, "Al menos usaste las mias primero...", "VAMPIRE2_NOTE3", 22);
        addLineSafe(lines_with_constant, "Arthur Holmwood", "VAMPIRE2_NOTE4", 22);

        addLineSafe(lines_with_constant, "2 de deciembre, 1898", "ENDING_LINE1", 17);
        addLineSafe(lines_with_constant, "Aún no sé como sentirme acerca", "ENDING_LINE2", 17);
        addLineSafe(lines_with_constant, "de los eventos que sucedieron", "ENDING_LINE3", 17);
        addLineSafe(lines_with_constant, "en la mansión Westen... digo", "ENDING_LINE4", 17);
        addLineSafe(lines_with_constant, "Westenra...", "ENDING_LINE5", 17);

        addLineSafe(lines_with_constant, "Aunque me alivia haber liberado", "ENDING_LINE6", 17);
        addLineSafe(lines_with_constant, "al mundo de esas béstias y", "ENDING_LINE7", 17);
        addLineSafe(lines_with_constant, "seguir con vida, me entristece", "ENDING_LINE8", 17);
        addLineSafe(lines_with_constant, "saber que la vida de mi buen", "ENDING_LINE9", 17);
        addLineSafe(lines_with_constant, "amigo terminó por culpa de", "ENDING_LINE10", 17);
        addLineSafe(lines_with_constant, "dichas criaturas...", "ENDING_LINE11", 17);
        addLineSafe(lines_with_constant, "Espero de verdad no tener que", "ENDING_LINE12", 17);
        addLineSafe(lines_with_constant, "regresar nunca a esta casa...", "ENDING_LINE13", 17);
        addLineSafe(lines_with_constant, "Profesor Edward Kelvin", "ENDING_LINE14", 17);

        addLineSafe(lines_with_constant, "Gracias por jugar a ", "ENDING2_LINE1", 17);
        addLineSafe(lines_with_constant, "Westen House", "ENDING2_LINE2", 17);
        addLineSafe(lines_with_constant, "Santiago Ontañón, 2021", "ENDING2_LINE3", 17);
        addLineSafe(lines_with_constant, "santi.ontanon@gmail.com", "ENDING2_LINE4", 17);
        addLineSafe(lines_with_constant, "Testeo: Jordi Sureda", "ENDING2_LINE5", 17);
        
        
        List<Integer> capitals = font.convertStringToAssembler("ABCDEFGHIJKLMNOPQRSTUVWXYZ ");
        System.out.println("Capitals: " + capitals);
        
        
        for(String s:lines_with_constant.keySet()) {
            if (!lines.contains(s)) lines.add(s);
        }


        // List<String> newlines = lines;
        List<String> newlines = optimizeGrouppings(lines, font, 512);
        // List<String> newlines = optimizeGrouppings(lines, font, 600);
        // List<String> newlines = optimizeGrouppings(lines, font, 640);
        // List<String> newlines = optimizeGrouppings(lines, font, 700);
//         List<String> newlines = optimizeGrouppings(lines, font, 4096);
        
        HashMap<String, Pair<Integer, Integer>> ids = new HashMap<>();
        Pair<List<Integer>,List<Integer>> sizes = EncodeText.encodeTextInBanks(newlines, font, 512, "src/autogenerated", "textBank-es", ids, "zx0");
        int size_before = 0;
        int size_after = 0;
        for(Integer size:sizes.m_a) size_before += size;
        for(Integer size:sizes.m_b) size_after += size;
        System.out.println("Total size before: " + size_before);
        System.out.println("Total size after: " + size_after);
        // String constants:
        {
            FileWriter fw = new FileWriter(new File("src/autogenerated/text-constants-es.asm"));
            for(String s:lines_with_constant.keySet()) {
                fw.write("TEXT_"+lines_with_constant.get(s)+"_BANK:   equ " + ids.get(s).m_a + "\n");
                fw.write("TEXT_"+lines_with_constant.get(s)+"_IDX:   equ " + ids.get(s).m_b + "\n");            
            }
            fw.flush();
            fw.close();
        }
    }
    
    
    public static void addLineSafe(HashMap<String,String> lines_with_constant, String line, String tag, int maxWidthInTiles) throws Exception
    {
        if (font.stringWidth(line) > maxWidthInTiles*8) {
            throw new Exception("'"+line+"' is wider than " + maxWidthInTiles + " tiles! (" + font.stringWidth(line) + " pixels, vs " + maxWidthInTiles*8 + ")");
        }
        lines_with_constant.put(line, tag);
    }
    
    
    public static List<String>  optimizeGrouppings(List<String> input_lines, PAKFont font, int group_size) throws Exception
    {
        List<String> bestLines = null;
//        EncodeText.compressor = "zx0";
        int best_size = 0;
        int best_seed = 0;      // seed 234: 1899 (for group_size 512, with 0.5 lateral moves)
                                // seed 0: 1903 (for group size 600)
                                // seed 3: 1874 (for group size 640)
                                // seed 6: 1850 (for group size 700)
        for(int seed = 0;seed<0+1;seed++) {
//        for(int seed = 0;seed<1000;seed++) {
//        for(int seed = 234;seed<234+1;seed++) {

            Pair<List<String>,Integer> tmp = optimizeGrouppingsInternal(input_lines, font, group_size, seed);
            if (bestLines == null || tmp.m_b < best_size) {
                bestLines = tmp.m_a;
                best_size = tmp.m_b;
                best_seed = seed;
                System.out.println("new best_size: " + best_size + " (best_seed: " + best_seed + ")");
            }
        }
        
        System.out.println("final best_size: " + best_size + " (best_seed: " + best_seed + ")");
        return bestLines;
    }
    
    
    public static Pair<List<String>,Integer>  optimizeGrouppingsInternal(List<String> input_lines, PAKFont font, int group_size, int seed) throws Exception  
    {
        String compressorDuringOptimization = "pletter";
        String targetCompressor = "zx0";
        Random r = new Random();
        r.setSeed(seed);

        List<String> lines = new ArrayList<>();
        lines.addAll(input_lines);
        Collections.shuffle(lines, r);
        int initial_size = EncodeText.estimateSizeOfAllTextBanks(lines, font, group_size, compressorDuringOptimization);
        int best = initial_size;
        System.out.println("Original order size: " + initial_size + " (with target compressor: " + 
                EncodeText.estimateSizeOfAllTextBanks(lines, font, group_size, targetCompressor) + ")");
        System.out.println("Initial size (seed " + seed + "):" + initial_size);

        double threshold = 1.0; // 1.0 means doing it sistematically, lower values run faster, but might not result in the best results
        double temperature = 0.0;
        double temperature_decay = 0.8;
        boolean repeat = true;
        // boolean repeat = false;
        while(repeat){
            repeat = false;
            System.out.println("temperature: " + temperature);
            for(int idx1 = 0;idx1<lines.size();idx1++) {
                // System.out.println(idx1 + "");
                for(int idx2 =idx1+1;idx2<lines.size();idx2++) {
                    if (r.nextDouble() > threshold) continue;
                    String tmp1 = lines.get(idx1);
                    String tmp2 = lines.get(idx2);
                    lines.set(idx1, tmp2);
                    lines.set(idx2, tmp1);

                    int size = EncodeText.estimateSizeOfAllTextBanks(lines, font, group_size, compressorDuringOptimization);
                    if (size < best) {
                        System.out.print(size + " ");
                        best = size;
                        repeat = true;
                    } else if (size == best && r.nextDouble() > 0.5) {
                        System.out.print(size + "* ");
                        best = size;
                        // repeat = true;
                    } else {
                        if (r.nextDouble() > temperature) {
                            // undo the swap:
                            lines.set(idx1, tmp1);
                            lines.set(idx2, tmp2);
                        } else {
                            System.out.println("- temperature ("+temperature+") induced random swap: " + size);
                            best = size;
                            repeat = true;                            
                        }
                    }
                }
            }
            System.out.println("");
            temperature *= temperature_decay;
            /*
            if (!repeat && !compressorDuringOptimization.equals(targetCompressor)) {
                // At the end do one round with the target compressor:
                compressorDuringOptimization = targetCompressor;
                best = EncodeText.estimateSizeOfAllTextBanks(lines, font, group_size, targetCompressor);
                repeat = true;
            }*/
            // repeat = false;
        }
        
        // System.out.println(lines);
        System.out.println("After optimization: " + EncodeText.estimateSizeOfAllTextBanks(lines, font, group_size, targetCompressor));
        
        return new Pair<>(lines, best);
    }
}
