    include "constants.asm"
    include "autogenerated/text-constants.asm"

; the first time this is compiled, we need a few symbols to be defined 
; to bootstrap the process. Comment the inclusion of trition.sym and Uncomment these 
; constant definition lines:
    include "../isometric.sym"
        
    org CUTSCENE_COMPRESSED_CODE_START

    include "compressed-state-cutscene.asm"
