    include "constants.asm"
IF SPANISH = 1
    include "autogenerated/text-constants-es.asm"
ELSE
    include "autogenerated/text-constants.asm"
ENDIF

; the first time this is compiled, we need a few symbols to be defined 
; to bootstrap the process. Comment the inclusion of trition.sym and Uncomment these 
; constant definition lines:
    include "../isometric.sym"
    
; ending variables:
ending_trigger_map:                 equ ram_to_clear_at_game_start+7  ; 0/1: map 1 triggered/loaded 2/3: map 2; 4/5: map 3
ending_roll_step:                   equ ram_to_clear_at_game_start+8  ; from 3-21: unrolling, from 103-121: rolling, 128: reset

ending_text_page_line_state:        equ ram_to_clear_at_game_start+9  ; 0: we still need to draw it, > 0 we are displaying it
ending_text_page:                   equ ram_to_clear_at_game_start+10  ; 0 (text 1), 1 (wait), 2 (text 2), 3 (wait), 4 (the end)
ending_text_page_line:              equ ram_to_clear_at_game_start+11
    
    org ENDING_COMPRESSED_CODE_START

    include "compressed-state-ending.asm"
